### ISSUE TITLE
Copy tooltip shows up behind navigation bar

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/components#42]
Likely need to increase the z-index to make it show up over the navigation bar in [mint](https://github.com/mintlify/mint)

<img width="453" alt="tooltip" src="https://user-images.githubusercontent.com/110702161/215008670-300371f7-08f1-4d73-a620-25475f1a952a.png">

**Comment by NicoZweifel** [comment]
Another one of those, nice catch :P

**Comment by NicoZweifel** [comment]
I had the same issue on the right side in this [PR](https://github.com/mintlify/components/pull/39/files), but decided to use shorter text here.
If you prefer `click to copy` I could revert to that when changing `z-index` works, but I feel like it is a bit odd to have the longer version instead of just `copy`.

**Comment by NicoZweifel** [comment]
It seems that this happens only for Grouped Code Blocks because the normal Code Blocks have a top margin.
I am ivestigating this issue here:https://github.com/mintlify/components/pull/43

**Comment by tobias-mintlify** [comment]
@NicoZweifel I tested `mint` with the new z-index but the `backdrop-blur` class on the navigation bar is still blurring the component despite the z-index being higher. Seems like the backdrop-blur affects components regardless of z-index. There are other steps required to avoid blurring the tooltip when I searched StackOverflow for this problem.

Can you look into how to get the backdrop-blur not to affect the tooltip?

**Comment by NicoZweifel** [comment]
Yeah I can take a look tomorrow 👍

**Comment by NicoZweifel** [comment]
When the new components [version ](https://github.com/mintlify/components/pull/49) is published, I can continue and merge this: https://github.com/mintlify/mint/pull/299

**Comment by tobias-mintlify** [comment]
Issue is fixed for most code blocks except for the right-side bar ones that have `sticky` set.

**Comment by NicoZweifel** [comment]
@tobias-mintlify It is because of a new StackingContext. you can read about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

"A stacking context is formed, anywhere in the document, by any element in the following scenarios:

- Root element of the document (<html>).
- Element with a [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) value absolute or relative and [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) value other than auto.
- Element with a [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) value fixed or sticky (sticky for all mobile browsers, but not older desktop browsers)."

**Comment by tobias-mintlify** [comment]
Let's get rid of `sticky` on the navbar then. I was messing around with it and we could use `fixed` instead of `sticky` then we just need margin/padding/a spacer div so the content doesn't show up under the nav bar until the page loads.

**Comment by NicoZweifel** [comment]
Sounds good, I could take a look today/tomorrow.

**Comment by tobias-mintlify** [comment]
All the edge cases are fixed! Thank you for all the help @NicoZweifel 🥳
