### ISSUE TITLE
Tree-shaking

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/components#60]
None of the primary maintainers of this repo are experts in tree-shaking. We would appreciate someone taking a look and making sure tree-shaking is set up correctly. The package has a lot of components and we don't want them being imported on pages that don't use them.

**Comment by NicoZweifel** [comment]
I have some experience with this and can take a look at this with next bundle analyzer, but it depends mainly on the client/app, more specifically how the library imports and exports its files (entrypoints used and imports of files from lib),
and also how the client imports.

To get the best results with tree-shaking it might be required to limit the main entrypoint index exports to stuff that gets used a lot and does not reference too much third party libs.
We could then use more specific entrypoints for imports that dont get used a lot and/or require additional dependencies, for example in the case of CodeBlock:
```ts
import {
  CodeBlock,
  CodeBlockProps,
  CodeBlockPropsBase,
  CodeGroup,
  CodeGroupProps,
  CodeGroupPropsBase,
} from "./Code";
```
Create a new EntryPoint/Bundle and Instead of 
```ts
import { CodeBlock as GenericCodeBlock } from '@mintlify/components';
```
use new entry point:
```ts
import { CodeBlock as GenericCodeBlock } from '@mintlify/components/CodeBlock';
```
In this case it would help with not loading ```@headlessui/react``` unnecessarily.
Futhermore we could add lazy loading for these imports which could improve first loading time/paint.

These Steps aren't always required to tree-shake, it depends on imports/exports in the client and lib (imports/exports used in the lib to reference other files of the lib).

Sometimes a single import somewhere in the lib imports a lot of files/bundles just from a single type import.
Because it imports from the entry point, a complete new tree of imports is triggered.

I can research this for components and the mint client a bit more, but I am getting an Error when building the mint client for production:

![image](https://user-images.githubusercontent.com/34443492/218443289-71ae302c-9236-4558-b78e-8b30b31541f7.png)

I am able to use the bundle analyzer tho and can see that the first load bundles are already pretty large and everything is loaded together, you can see here how headless-ui, and other third party dependencies are loaded in one bundle, while all of components is loaded in another bundle:

![image](https://user-images.githubusercontent.com/34443492/218443621-087ab6d1-8d41-4161-95c1-b0cf9d59d64d.png)

I can play around with en empty doc project and see if the bundle sizes will change but probably we will have to do a bit more, especially if we want to split bundles and lazy load third party code (in the case of Logrocket, afaik this isn't possible, I've tried a few months ago 😄).
But for axios it is not a problem, for example. Should also be able to split the bundle for headless-ui, but it might require changing exports/imports in components to tree-shake.

**Comment by NicoZweifel** [comment]
When using [this ](https://github.com/mintlify/mint/pull/360) and a modified version of `components` that does not use CodeBlock/Group exports in index, the bundle size goes down.

![image](https://user-images.githubusercontent.com/34443492/218526594-39c7c984-0c0f-4693-ad32-78697465bc16.png)

To significantly reduce bundle size, imports should be adjusted for all heavy components or files that use third party dependencies like headless/axios.
We could also add a way to export the sub modules without `dist` but that will require some more work and/or changes to the webpack config.

**Comment by tobias-mintlify** [comment]
I'm fixing the production build issue you just saw so we can test this fully. Should have a PR up within an hour.

**Comment by tobias-mintlify** [comment]
@NicoZweifel just talked with Hahnbee about fixing the production issue you saw. She says you need to be on Node v18+ and the latest Next.js to use `structuredClone`. Let me know if the issue still occurs after updating.

**Comment by tobias-mintlify** [comment]
By the way, if we manage to optimize the rest of this I'm down to remove the Logrocket implementation for the sake of speed. :)

**Comment by NicoZweifel** [comment]
It's definitely possible to get sub 100kb first load with logrocket, next + react (it is even with something heavier like mui), but it will probably require lazy loading of some parts.

**Comment by NicoZweifel** [comment]
I also noticed that it will be hard to tree-shake any components from the library because `SupremePageLayout` references `components/index.ts`, which imports the main entrypoint of  `@mintlify/components`.

A solution is to remove the `CodeBlock` or other components from `index.ts` in `@mintlify/components` and import it like this: `@mintlify/components/CodeBlock`

**Comment by tobias-mintlify** [comment]
That error looks like there's a README file we're trying to render as a page and failing. Can you check if you have any of those in the `client` folder?

As you called out, `mint` always imports everything. We need to do is only import components a page uses. That might require us to write a remark plugin to dynamically add the necessary imports to pages. If you think this package is fine for tree shaking we can move this ticket to `mint`.

**Comment by NicoZweifel** [comment]
Exactly. A combination of checking for required components and then having dynamic imports that get conditionally put into an array and passed to `MDXRemote` is what I was thinking of.

> If you think this package is fine for tree shaking we can move this ticket to mint.

We can create an issue in `mint` called `tree-shaking/lazy-loading` and keep this one to tree-shaking in `components`.

I researched lazy loading in `mint` and tree-shaking on a branch and was able to split the bundle significantly, which should improve performance, especially in dev.

Tree-shaking can still be improved in both `components` and the client.

Since these topics are very related I am gaining an overview of how imports, exports and dependencies are connected in this project and what can and can't be tree shaked/lazy loaded.

I will need some more time on this though, since some dependencies are easier to split than others. 
They are sometimes referenced by each other, making these kind of issues feel like untying a knot (which I kinda like 😆).

These are some of the findings:

good:
- any Dialogs/Popups and their dependencies can be lazy loaded by default.
- This affects dialogs in `NavPopover`, `Search` and `Navbar`. Their dependencies can be lazy loaded (agorasearch etc).
- able to lazy load `headlessui`, `agorasearch` and others as a result.
- react-markdown can be lazy loaded.
- anything used for requests / responses and apiPlayground can be lazy loaded.
- `axios` can be lazy loaded but could be not worth it, if we always need it anyway.
- able to split imports and bundle used for any Code component, should in theory mean treeshaking is possible, if there is no index import.

bad:
- `@segment` seems to not be possible to lazy load.
- `logrocket` is not possible afaik to be lazy loaded (or will have issues, if it is).

Here is how the bundles look in this state:

![image](https://user-images.githubusercontent.com/34443492/219330270-a7257103-afe3-41a8-82cb-5cd2fb1747e9.png)

The main bundle is now only ~50kb zipped instead of ~130kb zipped and the components bundle is smaller as well since anything related to Code components is split of into another bundle.
The shared first load size should be smaller as well.

Right now  `components` are shakeable if you import everything through `dist`.
This is kinda ugly and can be improved in multiple ways, that are all not ideal unfortunately.

- Create more packages/webpack bundles. This one is quite clear I think but I don't think the pros outweigh the cons.
  I think that there is not enough code yet in `components` to consider having multiple packages/entrypoints. This can also 
  increase bundle size at first.

- Use tsconfig paths in the client. This one is fine if components are only meant to be used by mintlify. Will require adding docs on tree shaking and requires every user of `components` to add the path, otherwise he can only import with 'dist' in the path.

- Put package.json in dist and change script paths/gitignore - This one works but I really don't like putting/copying package.json into `dist`. I think it is kinda hacky. Let me know what you think.

- Use package.jsons + inheritance + existing ts submodules.
I think this one suits as best at the moment. We can create a new folder and package,json which inherits the base json and points to the folder/index you want to have as a seperate export/import. 
Easier to adapt if moving to the first option later on.

I can create an example to demonstrate the last option.
I am also looking into if `SideEffetcs` makes a difference for some of our components: https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects

Shaking works better if our client would use the unbundled files,
but I think we should keep it like that, because that is how the library is intended to be used.

I might add some tests in components to check for tree shaking automatically.

**Comment by NicoZweifel** [comment]
> That error looks like there's a README file we're trying to render as a page and failing. Can you check if you have any of those in the client folder?

I'll try to narrow down the issue, I tried using almost empty docs and the mint docs so far.

I'm really excited to run some performance tests on the production build soon 🚀

**Comment by NicoZweifel** [comment]
I was able to resolve the error, I created an [issue](https://github.com/mintlify/mint/issues/413) related to it.

**Comment by NicoZweifel** [comment]
I think the library is fine for tree shaking, I changed `headlessui` to peerdependencies in another PR but
other than that I think we will have to handle shaking in the client by not using the main entrypoint of `components`.

Continuing the discussion about lazy loading/ tree shaking [here](https://github.com/mintlify/mint/issues/383).

**Comment by tobias-mintlify** [comment]
Closing the issue since `components` seems okay for now 🚀  We'll continue the conversation in `mint`.
